import shutil, os

# This is a list of cities, follow this format: [cityName, stateName, stateAbbr]
cities = [
  ["San Diego", "California", "CA"],
  ["New York City", "New York", "NY"],
  ["Boston", "Massachusetts", "MA"],
  ["Washingto DC", "District of Columbia", "DC"],
  ["Houston", "Texas", "TX"],
  ["Austin", "Texas", "TX"],
  ["San Antonio", "Texas", "TX"],
  ["Chicago", "Illinois", "IL"],
  ["East Lansing", "Michigan", "MI"],
  ["Ann Arbor", "Michigan", "MI"],
  ["Providence", "Rhode Island", "RI"],
  ["Pittsburgh", "Pennsylvania", "PA"],
  ["Philadelphia", "Pennsylvania", "PA"],
  ["Vancouver", "British Columbia", "BC"],
  ["Portland", "Oregon", "OR"],
  ["Phoenix", "Arizona", "AZ"],
  ["San Francisco", "California", "CA"],
  ["Oakland", "California", "CA"],
  ["Berkeley", "California", "CA"],
  ["Hayward", "California", "CA"],
  ["Fremont", "California", "CA"],
  ["San Jose", "California", "CA"],
  ["Sunnyvale", "California", "CA"],
  ["Palo Alto", "California", "CA"],
  ["Menlo Park", "California", "CA"],
  ["Milpitas", "California", "CA"],
  ["Mountain View", "California", "CA"],
  ["Stanford", "California", "CA"],
  ["Los Angeles", "California", "CA"],
#  ["Detroit", "Michigan", "MI"],
#  ["Atlanta", "Georgia", "GA"],
#  ["Raleigh", "North Carolina", "NC"],
#  ["Dallas", "Texas", "TX"],
#  ["Tacoma", "Washington", "WA"],
  ["Seattle", "Washington", "WA"]
]

# These keywords will be put into sentences, so
# please end with conference so that the sentences make sense.
conferenceKeywords = [
  "AI conference",
  "Artificial Intelligence conference",
  "machine learning conference",
  "deep learning conference",
  "NLP conference"
]

def urlize(s):
  return s.lower().replace(' ', '-')

# Clean up the previous versions of generated by this script
for city in cities:
  state = city[1]
  try:
    shutil.rmtree("./" + urlize(state))
  except:
    pass

# NOW LETS DO SOME MASS CREATION BABY!
counter = 0
for city in cities:
  city_name = city[0]
  state_name = city[1]
  state_abbr = city[2]

  for keyword in conferenceKeywords:
    directory = os.path.join(urlize(state_name), urlize(city_name), urlize(keyword))
    print(directory)
    if not os.path.exists(directory):
      os.makedirs(directory)
      with open(os.path.join(directory, 'index.md'), 'w') as outfile:
        content = ("---\n"
                  "title: AI Frontiers Conference\n"
                  "layout: index\n"
                  "cityKeyword: '%s'\n"
                  "stateKeyword: '%s'\n"
                  "stateAbbrKeyword: '%s'\n"
                  "conferenceKeyword: '%s'\n"
                  "---") % (city_name, state_name, state_abbr, keyword)
        outfile.write(content)
      counter += 1

print("phew! %d files generated." % counter)
