import shutil, os

# This is a list of cities, follow this format: [cityName, stateName, stateAbbr]
cities = [
  ["San Diego", "California", "CA"],
  ["Los Angleles", "California", "CA"],
  ["New York City", "New York", "NY"],
  ["Boston", "Massachusetts", "MA"],
  ["Washingto DC", "District of Columbia", "DC"],
  ["Houston", "Texas", "TX"],
  ["Austin", "Texas", "TX"],
  ["San Antonio", "Texas", "TX"],
  ["Chicago", "Illinois", "IL"],
  ["East Lansing", "Michigan", "MI"],
  ["Ann Arbor", "Michigan", "MI"],
  ["Providence", "Rhode Island", "RI"],
  ["Pittsburgh", "Pennsylvania", "PA"],
  ["Philadelphia", "Pennsylvania", "PA"],
  ["Vancouver", "British Columbia", "BC"],
  ["Portland", "Oregon", "OR"],
  ["Phoenix", "Arizona", "AZ"],
  ["Napa", "California", "CA"],
  ["Fairfield", "California", "CA"],
  ["Dixon", "California", "CA"],
  ["Sonoma", "California", "CA"],
  ["Petaluma", "California", "CA"],
  ["Rio Vista", "California", "CA"],
  ["Travis Afb", "California", "CA"],
  ["American Canyon", "California", "CA"],
  ["Novato", "California", "CA"],
  ["Birds Landing", "California", "CA"],
  ["Vallejo", "California", "CA"],
  ["Benicia", "California", "CA"],
  ["Nicasio", "California", "CA"],
  ["Oakley", "California", "CA"],
  ["Crockett", "California", "CA"],
  ["Port Costa", "California", "CA"],
  ["Suisun City", "California", "CA"],
  ["San Francisco", "California", "CA"],
  ["Pittsburg", "California", "CA"],
  ["San Rafael", "California", "CA"],
  ["Concord", "California", "CA"],
  ["Rodeo", "California", "CA"],
  ["Martinez", "California", "CA"],
  ["Hercules", "California", "CA"],
  ["San Geronimo", "California", "CA"],
  ["Lagunitas", "California", "CA"],
  ["Alameda", "California", "CA"],
  ["Antioch", "California", "CA"],
  ["San Anselmo", "California", "CA"],
  ["Brentwood", "California", "CA"],
  ["Fairfax", "California", "CA"],
  ["Woodacre", "California", "CA"],
  ["Forest Knolls", "California", "CA"],
  ["Walnut Creek", "California", "CA"],
  ["Pinole", "California", "CA"],
  ["Richmond", "California", "CA"],
  ["San Pablo", "California", "CA"],
  ["El Sobrante", "California", "CA"],
  ["Oakland", "California", "CA"],
  ["Pleasant Hill", "California", "CA"],
  ["Greenbrae", "California", "CA"],
  ["Lafayette", "California", "CA"],
  ["Clayton", "California", "CA"],
  ["Larkspur", "California", "CA"],
  ["San Quentin", "California", "CA"],
  ["El Cerrito", "California", "CA"],
  ["Corte Madera", "California", "CA"],
  ["Berkeley", "California", "CA"],
  ["Mill Valley", "California", "CA"],
  ["Orinda", "California", "CA"],
  ["Byron", "California", "CA"],
  ["Stinson Beach", "California", "CA"],
  ["Albany", "California", "CA"],
  ["Alamo", "California", "CA"],
  ["Sausalito", "California", "CA"],
  ["Moraga", "California", "CA"],
  ["Belvedere Tiburon", "California", "CA"],
  ["Livermore", "California", "CA"],
  ["Emeryville", "California", "CA"],
  ["Diablo", "California", "CA"],
  ["Danville", "California", "CA"],
  ["San Ramon", "California", "CA"],
  ["Castro Valley", "California", "CA"],
  ["Pleasanton", "California", "CA"],
  ["San Leandro", "California", "CA"],
  ["Dublin", "California", "CA"],
  ["Daly City", "California", "CA"],
  ["Brisbane", "California", "CA"],
  ["San Lorenzo", "California", "CA"],
  ["Hayward", "California", "CA"],
  ["Pacifica", "California", "CA"],
  ["Sunol", "California", "CA"],
  ["South San Francisco", "California", "CA"],
  ["Union City", "California", "CA"],
  ["San Bruno", "California", "CA"],
  ["San Mateo", "California", "CA"],
  ["Half Moon Bay", "California", "CA"],
  ["Millbrae", "California", "CA"],
  ["Fremont", "California", "CA"],
  ["Moss Beach", "California", "CA"],
  ["Burlingame", "California", "CA"],
  ["Newark", "California", "CA"],
  ["Redwood City", "California", "CA"],
  ["Atherton", "California", "CA"],
  ["Belmont", "California", "CA"],
  ["San Carlos", "California", "CA"],
  ["San Jose", "California", "CA"],
  ["Alviso", "California", "CA"],
  ["Sunnyvale", "California", "CA"],
  ["Palo Alto", "California", "CA"],
  ["Menlo Park", "California", "CA"],
  ["Milpitas", "California", "CA"],
  ["Mount Hamilton", "California", "CA"],
  ["Mountain View", "California", "CA"],
  ["Stanford", "California", "CA"],
  ["Portola Valley", "California", "CA"],
  ["Los Altos", "California", "CA"]
]

# These keywords will be put into sentences, so
# please end with conference so that the sentences make sense.
conferenceKeywords = [
  "AI conference",
  "machine learning conference",
  "deep learning conference",
  "NLP conference",
  "Drone conference",
]

def urlize(s):
  return s.lower().replace(' ', '-')

# Clean up the previous versions of generated by this script
for city in cities:
  state = city[1]
  try:
    shutil.rmtree("./" + urlize(state))
  except:
    pass

# NOW LETS DO SOME MASS CREATION BABY!
# counter = 0
# for city in cities:
#   city_name = city[0]
#   state_name = city[1]
#   state_abbr = city[2]

#   for keyword in conferenceKeywords:
#     directory = os.path.join(urlize(state_name), urlize(city_name), urlize(keyword))
#     print(directory)
#     if not os.path.exists(directory):
#       os.makedirs(directory)
#       with open(os.path.join(directory, 'index.md'), 'w') as outfile:
#         content = ("---\n"
#                   "title: AI Frontiers Conference\n"
#                   "layout: index\n"
#                   "cityKeyword: '%s'\n"
#                   "stateKeyword: '%s'\n"
#                   "stateAbbrKeyword: '%s'\n"
#                   "conferenceKeyword: '%s'\n"
#                   "---") % (city_name, state_name, state_abbr, keyword)
#         outfile.write(content)
#       counter += 1

# print("phew! %d files generated." % counter)
