import shutil, os

# This is a list of cities, follow this format: [cityName, stateName, stateAbbr]
cities = [
  ["San Diego", "California", "CA"],
  ["Los Angleles", "California", "CA"],
  ["New York City", "New York", "NY"],
  ["Boston", "Massachusetts", "MA"],
  ["Washingto DC", "District of Columbia", "DC"],
  ["Houston", "Texas", "TX"],
  ["Austin", "Texas", "TX"],
  ["San Antonio", "Texas", "TX"],
  ["Chicago", "Illinois", "IL"],
  ["East Lansing", "Michigan", "MI"],
  ["Ann Arbor", "Michigan", "MI"],
  ["Providence", "Rhode Island", "RI"],
  ["Pittsburgh", "Pennsylvania", "PA"],
  ["Philadelphia", "Pennsylvania", "PA"],
  ["Vancouver", "British Columbia", "BC"],
  ["Portland", "Oregon", "OR"],
  ["Phoenix", "Arizona", "AZ"],
  # ["Napa", "California", "CA"],
  # ["Fairfield", "California", "CA"],
  # ["Sonoma", "California", "CA"],
  # ["Petaluma", "California", "CA"],
  # ["Novato", "California", "CA"],
  # ["Birds Landing", "California", "CA"],
  # ["Vallejo", "California", "CA"],
  # ["San Francisco", "California", "CA"],
  # ["Pittsburg", "California", "CA"],
  # ["Concord", "California", "CA"],
  # ["Richmond", "California", "CA"],
  # ["San Pablo", "California", "CA"],
  # ["El Sobrante", "California", "CA"],
  # ["Oakland", "California", "CA"],
  # ["Pleasant Hill", "California", "CA"],
  # ["El Cerrito", "California", "CA"],
  # ["Berkeley", "California", "CA"],
  # ["Sausalito", "California", "CA"],
  # ["Livermore", "California", "CA"],
  # ["Emeryville", "California", "CA"],
  # ["Diablo", "California", "CA"],
  # ["Castro Valley", "California", "CA"],
  # ["Pleasanton", "California", "CA"],
  # ["Daly City", "California", "CA"],
  # ["Hayward", "California", "CA"],
  # ["Union City", "California", "CA"],
  # ["San Bruno", "California", "CA"],
  # ["San Mateo", "California", "CA"],
  # ["Fremont", "California", "CA"],
  # ["Newark", "California", "CA"],
  # ["Redwood City", "California", "CA"],
  # ["San Jose", "California", "CA"],
  # ["Sunnyvale", "California", "CA"],
  # ["Palo Alto", "California", "CA"],
  # ["Menlo Park", "California", "CA"],
  # ["Milpitas", "California", "CA"],
  # ["Mountain View", "California", "CA"],
  ["Stanford", "California", "CA"],
  # ["Los Altos", "California", "CA"]
]

# These keywords will be put into sentences, so
# please end with conference so that the sentences make sense.
conferenceKeywords = [
  "AI conference",
  "machine learning conference",
  "deep learning conference",
  "NLP conference"
]

def urlize(s):
  return s.lower().replace(' ', '-')

# Clean up the previous versions of generated by this script
for city in cities:
  state = city[1]
  try:
    shutil.rmtree("./" + urlize(state))
  except:
    pass

# NOW LETS DO SOME MASS CREATION BABY!
counter = 0
for city in cities:
  city_name = city[0]
  state_name = city[1]
  state_abbr = city[2]

  for keyword in conferenceKeywords:
    directory = os.path.join(urlize(state_name), urlize(city_name), urlize(keyword))
    print(directory)
    if not os.path.exists(directory):
      os.makedirs(directory)
      with open(os.path.join(directory, 'index.md'), 'w') as outfile:
        content = ("---\n"
                  "title: AI Frontiers Conference\n"
                  "layout: index\n"
                  "cityKeyword: '%s'\n"
                  "stateKeyword: '%s'\n"
                  "stateAbbrKeyword: '%s'\n"
                  "conferenceKeyword: '%s'\n"
                  "---") % (city_name, state_name, state_abbr, keyword)
        outfile.write(content)
      counter += 1

print("phew! %d files generated." % counter)
